### ISSUE TITLE
Add contributers section in reademe 

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Quizzer#12]

**Comment by Ask-Subhasmita** [comment]
Hey, @Souvikns I would like to work on this issue, do you have any prerequisites for it?

**Comment by imabp** [comment]
@Ask-Subhasmita  we are happy to see that you are ready for contributing towards the documentation of Quizzer. We welcome you with your ideas for Documentation. No prerequisites yet.

**Comment by Ask-Subhasmita** [comment]
Hey @imabp can we use @all-contributors bot for automatically adding contributors to the list in the documentation section?

**Comment by Ask-Subhasmita** [comment]
Eg- @all-contributors add @Ask-Subhasmita for documentation

**Comment by Ask-Subhasmita** [comment]
Eg- @all-contributors please add @imabp for tests, code

**Comment by imabp** [comment]
👨‍💻Nice @Ask-Subhasmita , go ahead.

**Comment by Souvikns** [comment]
@all-contributors please add @Ask-Subhasmita  for content

**Comment by Souvikns** [comment]
Thanks, @Ask-Subhasmita I didn't know about this, this is actually awesome.

**Comment by Souvikns** [comment]
@all-contributors please add @Souvikns  for code

**Comment by Souvikns** [comment]
@all-contributors please add @imabp  for code

**Comment by Souvikns** [comment]
@all-contributors please add @rohitjethoe  for code

**Comment by imabp** [comment]
@all-contributors  wanna go out for chilled coke ? :) hope he answers🤭🤭

**Comment by imabp** [comment]
aww so cute @all-contributors come lets go for coke !!!

**Comment by imabp** [comment]
I have good intentions @all-contributors , wont harm you!!

**Comment by Ask-Subhasmita** [comment]
@Souvikns I am happy I could help!
@imabp we need to find a friendly one for you ;)
