### ISSUE TITLE
Create UI for creating questions

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Quizzer#13]

**Comment by malaikaaiyar** [comment]
Hey @Souvikns, can I try this one? Also do you have any ideas on what you want it to look like? Thanks!

**Comment by Souvikns** [comment]
@malaikaaiyar welcome to our repo. 
We are still deciding on the design, This is what I was thinking. 
![image](https://user-images.githubusercontent.com/41781438/90315235-76f22f00-df37-11ea-8c63-67049962d618.png)
--- 

This issue was just the base issue to decide on the design. You are welcome to share any ideas. Also designing a whole page will be a lot of work. I think breaking the whole design into smaller components will be better. I will break the design and create multiple issues, so stay tuned for that. You are also welcome to create a new pull request for any component that you would like to do.
