### ISSUE TITLE
Create routes for answering qizzes 

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Quizzer#14]

**Comment by thchong-code** [comment]
hmm, what do you mean? Do you mean submitting the quiz answer to the server? Do you mean: Say that option A is the correct ans and the user chooses option A and this route will check the answer with the server.

**Comment by Souvikns** [comment]
If you see our  [quiz schema](https://github.com/Ninja-Developers/Quizzer/blob/master/model/quiz.js), you will see that the user is already providing the correct answer. But when the users submit the question we make an HTTP request to store the data and also use socket to provide realtime feedback to the creator of the quiz.
