### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Quizzer#20]
![Index.png](https://images.zenhubusercontent.com/5e5c04ddd0668b3a2093f19f/208cbbee-736c-423e-9027-54111519585d)
---
> I am not a designer, this is just a basic design to get started. 
>##  Open To Any Suggestions or Idea

## Palette
- #F3B10E
- #F3B10E

---
## Images 
![undraw_questions_75e0](https://user-images.githubusercontent.com/41781438/90953363-676b6c80-e488-11ea-8674-b0f318491168.png)

---

**Comment by Deeksha-Rawat** [comment]
@Souvikns can I make this page for you?

**Comment by Souvikns** [comment]
yeah sure @Deeksha-Rawat have a try. I am assiging this issue to you

**Comment by Deeksha-Rawat** [comment]
thanks @Souvikns

**Comment by Deeksha-Rawat** [comment]
![screencapture-127-0-0-1-5500-index-html-2020-09-02-14_42_21](https://user-images.githubusercontent.com/50552823/91963666-c86a2e80-ed2b-11ea-971d-9c07ec51e53b.png)

**Comment by Deeksha-Rawat** [comment]
![screencapture-127-0-0-1-5500-index-html-2020-09-02-14_43_42](https://user-images.githubusercontent.com/50552823/91963714-de77ef00-ed2b-11ea-8df8-0fa7b3a6f8bf.png)

**Comment by Deeksha-Rawat** [comment]
these are the templates.hope you like it :) or you want any further correction:)😊
