### ISSUE TITLE
Create Login Page

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Quizzer#7]
## TODO
- [ ] Create a Login component in React following the design pattern bellow

![Auth.png](https://images.zenhubusercontent.com/5e5c04ddd0668b3a2093f19f/b2234ef5-cbea-4825-9aa3-c958f7a5e50d)

**Comment by christinealuo** [comment]
Hey @Souvikns I'm trying to find issues that I can contribute to as a first-timer and I have experience with React, was wondering if I could work on this 🤩

**Comment by Souvikns** [comment]
Yeah, @christinealuo I am assigning this issue to you.

**Comment by imabp** [comment]
Yes @christinealuo, you may proceed with the design. And feel free if you get stuck anywhere.

**Comment by Bob160** [comment]
Hi, 

I'm not familiar with React, only vanilla JavaScript but I'd like to try my hands on this if you'd guide me?

**Comment by Ask-Subhasmita** [comment]
@Souvikns @imabp If someone is not working on it I can help, perhaps I have one doubt, is this page going to be a serverless one?

**Comment by Souvikns** [comment]
No, this will not be a serverless application, it has a server and is using nodejs.

**Comment by Souvikns** [comment]
@Ask-Subhasmita you can work on it, we use material UI, but you can use CSS to. If you use material UI you get all the components like the card, button, and text field pre-made.

**Comment by Ask-Subhasmita** [comment]
![image](https://user-images.githubusercontent.com/57298668/91128677-3b3d2f00-e6c6-11ea-8c67-126e597c500c.png)

will this overview be okay?

**Comment by Ask-Subhasmita** [comment]
![image](https://user-images.githubusercontent.com/57298668/91128796-72134500-e6c6-11ea-9728-c3e656511f27.png)


@Souvikns  will this overview be okay?

**Comment by Souvikns** [comment]
wow this is looking awesome .

**Comment by Ask-Subhasmita** [comment]
@Souvikns  this is the final view, do mention if there are any changes to be done.

![image](https://user-images.githubusercontent.com/57298668/91135721-bce38b80-e6cb-11ea-8500-a198ea697853.png)

**Comment by imabp** [comment]
@Ask-Subhasmita I find font bit, okayish, Can you share some font ideas

**Comment by Ask-Subhasmita** [comment]
@imabp I find these minimal, anything fancy you suggest?

![image](https://user-images.githubusercontent.com/57298668/91144276-6b3dff80-e6d1-11ea-9abd-b9313a225c3a.png)


![image](https://user-images.githubusercontent.com/57298668/91144305-77c25800-e6d1-11ea-9481-e65da39e2aca.png)

**Comment by imabp** [comment]
Fonts like `Montserrat` and `Raleway ` looks great. 

For Raleway
https://fonts.google.com/specimen/Raleway

**Comment by Ask-Subhasmita** [comment]
@imabp  I've used Raleway in this.

**Comment by imabp** [comment]
Pardon @Ask-Subhasmita , then try once with `Montserrat` . I am so picky in Fonts !!

**Comment by Ask-Subhasmita** [comment]
@imabp  okay, I'll take that into account!

**Comment by master-bogdan** [comment]
Hello! I am beginner, but I have understanding of React ( You can go to my github page and see my projects). I would like to join in jour project and make this login page component

**Comment by imabp** [comment]
@master-bogdan Its good to see you interested. But we have planned this issue to assign to @Ask-Subhasmita, yes you may track this issue,  if it doesnt get solved soon, we will be assigning you this. Keep an eye on other issues too.

**Comment by master-bogdan** [comment]
@imabp oki docki

**Comment by Ask-Subhasmita** [comment]
Hey, @Souvikns @imabp  I've put up a pull request 5 days ago, I hope it gets reviewed soon. Thanks!

**Comment by Souvikns** [comment]
@Ask-Subhasmita, as we were not getting the free hosting for our application, we will be moving this application to next.js so give us some time as we have to update the whole codebase accordingly. your pr will get merged as the front will remain the same.

**Comment by imabp** [comment]
@Ask-Subhasmita , I know it feels exciting to see the purple color !!! (Merged). Right now, we are shifting whole code base to NextJS. 
Reason: We can create on instant backend apis

**Comment by Ask-Subhasmita** [comment]
@Souvikns @imabp It's alright, in the meantime I would keep eyeing more issues and bugs to solve, thank you for guiding me throughout. ;)

**Comment by imabp** [comment]
@Ask-Subhasmita I hope you have taken it positively👨‍💻🙌🙂. And not worry, we will not let everyone's amount 👩‍💻of handwork go in vane ! 😤
