### ISSUE TITLE
Signin with Google

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Quizzer#8]
- [ ] User passport js and google-oauth2 strategy to build sign with google functionality.

**Comment by ThanosDodd** [comment]
Hi, I just found this repo today, so sorry for the questions that probably have obvious answers.
1. Have you already created an app on the Google developers console? And if yes, have you placed the IDs in the .env file?

**Comment by dreplica** [comment]
Has this been fixed, i want to work on it?

**Comment by Souvikns** [comment]
This issue was put on hold, as it was not an immediate requirement.  still, you could work on this if you want
